# Generated by Django 4.2.2 on 2023-06-28 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainsupload',
            old_name='model',
            new_name='train',
        ),
    ]
