# Generated by Django 4.0.3 on 2023-06-30 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handle', '0002_rename_model_trainsupload_train'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestsUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.FileField(upload_to='tests/')),
            ],
        ),
    ]
